export const menuList={
    mainMenuList:[
        {text:'몸으로 말해요',url:'/body'},
        {text:'인물 퀴즈',url:'/people'},
    ],
    bodyLanguageSubject:[
        {text:'동물/곤충',value: 'animal', difficulty:'상', detail: '10문제, 배점 높음',url:'/quiz/body/animal'},
        {text:'영화',value: 'movie', difficulty:'중', detail: '15문제, 배점 낮음',url:'/quiz/body/movie'},
        {text:'감정/기분/표정/욕구',value: 'emotion', difficulty:'하', detail: '20문제, 배점 매우 낮음',url:'/quiz/body/emotion'},
    ],
    peopleQuizSubject:[
        {text:'그룹1',value: 'group1', difficulty:'중', detail: '10문제',url:'/quiz/people/group1'},
        {text:'그룹2',value: 'group2', difficulty:'중', detail: '10문제',url:'/quiz/people/group2'},
        {text:'그룹3',value: 'group3', difficulty:'중', detail: '10문제',url:'/quiz/people/group3'},
    ],
}

export const bodyLanguageContent={
    animal:[
        {text:'늑대', score:'10'},
        {text:'수달', score:'15'},
        {text:'문어', score:'10'},
        {text:'아나콘다', score:'20'},
        {text:'개미핥기', score:'25'},
        {text:'멸치', score:'15'},
        {text:'팬더', score:'15'},
        {text:'개미', score:'15'},
        {text:'독수리', score:'10'},
        {text:'매미', score:'15'},
    ],
    movie: [
        {text:'타이타닉', score:'10'},
        {text:'해리포터', score:'10'},
        {text:'명량', score:'10'},
        {text:'범죄도시', score:'10'},
        {text:'택시운전사', score:'10'},
        {text:'아저씨', score:'10'},
        {text:'아바타', score:'10'},
        {text:'겨울왕국', score:'10'},
        {text:'어벤져스', score:'10'},
        {text:'인터스텔라', score:'10'},
        {text:'인셉션', score:'10'},
        {text:'탑건', score:'10'},
        {text:'터미네이터', score:'10'},
        {text:'타짜', score:'10'},
        {text:'킹스맨', score:'10'},
    ],
    emotion:[
        {text:'윙크',score:'5'},
        {text:'짜증',score:'7'},
        {text:'화장실가고싶은',score:'10'},
        {text:'공포/무서움',score:'7'},
        {text:'부러움',score:'7'},
        {text:'부끄러움',score:'7'},
        {text:'행복한',score:'7'},
        {text:'웃긴',score:'7'},
        {text:'자신만만',score:'7'},
        {text:'지루한',score:'5'},
        {text:'졸린/피곤한',score:'7'},
        {text:'슬픔',score:'5'},
        {text:'비웃음',score:'5'},
        {text:'귀찮음',score:'10'},
        {text:'어색한',score:'10'},
        {text:'부담스러움',score:'7'},
        {text:'사랑에 빠진',score:'10'},
        {text:'신나는',score:'5'},
        {text:'화남',score:'7'},
        {text:'배부른',score:'10'},
        {text:'간지러움',score:'5'},
    ]
}